// flow-typed signature: 471780e5be79217c91495abeadb63b81
// flow-typed version: <<STUB>>/atra_v1.1.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atra/dist/atra.cjs' {
  declare module.exports: any;
}

declare module 'atra/dist/atra.es' {
  declare module.exports: any;
}

declare module 'atra/dist/atra.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atra/dist/atra.cjs.js' {
  declare module.exports: $Exports<'atra/dist/atra.cjs'>;
}
declare module 'atra/dist/atra.es.js' {
  declare module.exports: $Exports<'atra/dist/atra.es'>;
}
declare module 'atra/dist/atra.min.js' {
  declare module.exports: $Exports<'atra/dist/atra.min'>;
}
